### ISSUE TITLE
Explorer windows still tend to get incorrect focus

### ISSUE THREAD

**Issue by shiro** [jpginc/windows10DesktopManager#21]
Not a major issue, nonetheless pretty annoying in the daily workflow - if there are many explorer windows and the user switches screens a few times it often happens that the wrong one gets focus (especially on "my computer").

Is there no way to remember window handles and set focus accordingly (alt+tab is also quite visible and ugly)?

**Comment by jpginc** [comment]
I had noticed this behavior but it hadn't annoyed me enough to change it.  The reason it happens is because My Computer has the ahk_exe of "explorer.exe". I've updated the window check in this commit: b5ec31308c36c1ea0a9ee5585bb878183e0cfd99 

I agree that the alt+tab thing is a bit hacky but I don't know of a better way to do it. Any suggestions?

**Comment by shiro** [comment]
I just do simple scripting, but I'll look into it at some point.
Anyways, thanks for the commit, explorer got a little bit less annoying today ^^.

**Comment by jpgincus** [comment]
This is fixed now. I use winget,,list + a dll  call to check the windows desktop to find the appropriate window to focus
