### ISSUE TITLE
retain focus on windows

### ISSUE THREAD

**Issue by shiro** [jpginc/windows10DesktopManager#4]
It would be great if there was an option to remember the active window before switching at every desktop, so it would be focused once switched back.
I assume a simple alt+tab won't work, since it produces unexpected behaviour at rapid switching. You would probably need to store some window UUIDs, assuming that's doable.

**Comment by jpginc** [comment]
the active window before switching does get activated i believe...I think the issue is that the desktop is in every virtual desktop so when the desktop is active and you change to another virtual desktop it remains active. I added a check to see if explorere.exe is the active window after changing to another desktop and, if it is, hit alt-tab.
